#!/bin/sh
#
# Settings for VIM


# Install vim color schemes
if [[ ! -d "$HOME/.vim/colors" ]]; then
	mkdir -p "$HOME/.vim/colors"
fi

cp -Ri "$HOME/dotfiles/vim/colors/" "$HOME/.vim/colors/"


# Install vim autoloads
if [[ ! -d "$HOME/.vim/autoload" ]]; then
	mkdir -p "$HOME/.vim/autoload"
fi

cp -Ri "$HOME/dotfiles/vim/autoload/" "$HOME/.vim/autoload/"


exit 0