#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
# Install or update
if test $(which brew)
then
	echo "  Updating Homebrew for you."
	brew update
else
	echo "  Installing Homebrew for you."
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	
	# Tap dupes
	brew tap homebrew/dupes
	# Install homebrew packages
	brew install \
		bash \
		bash-completion \
		colordiff \
		ffmpeg \
		git \
		mysql \
		rsync \
		wget \
		zsh;
	
	# Install caskroom
	brew install casks
	brew cask install \
		1password \
		acorn \
		atom \
		brackets \
		chrome-devtools
		dropbox	\
		firefox \
		google-chrome \
		google-drive \
		handbrake \
		imageoptim \
		quicksilver \
		qlcolorcode \
		quicklook-csv \
		quicklook-json \
		qlmarkdown \
		sequel-pro \
		sketch \
		sqlitebrowser \
		textmate \
		textwrangler \
		transmit \
		virtualbox \
		virtualbox-extension-pack \
		vagrant;

fi

exit 0
