#!/bin/sh
#
# Homebrew
#
# This installs and updates some of the common dependencies needed (or at least desired)
# using Homebrew and Caskroom

# @todo create a skip list for casks that fail (because maybe they were already installed). Don't want to keep trying to install them

# Default Homebrew packages to install
# Add new ones here
DEFAULT_PKGS=(
	bash 				
	bash-completion
	bat
	brew-cask-completion
	colordiff
	coreutils
	diffutils
	duti
	fd		
	ffmpeg
	gawk 				
	git			
	mysql
	ncdu 				 
	rsync
	the_silver_searcher			
	wget
	wp-cli
	wp-cli-completion		
	zsh 
)

# Default Caskroom packages to install
# Add new ones here
DEFAULT_CASKS=(				
	1password 					
	acorn 						
	atom 							
	bbedit
	brackets 					
	chrome-devtools			
	dropbox	
	firefox 
	google-chrome 
	handbrake 
	imageoptim 
	quicksilver 
	qlcolorcode 
	quicklook-csv 
	quicklook-json 
	qlmarkdown 
	sequel-pro 
	sketch 
	#sqlitebrowser 
	textmate 
	transmit 
	virtualbox 
	virtualbox-extension-pack 
	vagrant 
)



# Interaction functions
info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}


contains() {
	[[ $1 =~ (^|[[:space:]])"$2"($|[[:space:]]) ]] && return 0  || return 1
}


# Check for Homebrew
# Install or update
if test $(which brew)
then
	info "Updating Homebrew for you..."
	brew update
else
	info "Installing Homebrew for you..."
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi


# Check to make sure we have all default brew packages
installed_pkgs=$(brew list)
install_list=()


# build list of packages to install
for i in "${DEFAULT_PKGS[@]}"
do
	contains "$installed_pkgs" $i
	r=$?
	if [[ "$r" -eq 1 ]] 
	then 
		#echo "$i added to install list"
		install_list+=("$i")
	else
		echo "$i already installed"
	fi
done

# Install homebrew packages
if [ ${#install_list[@]} -eq 0 ]
then 
	success "All default Homebrew packages already installed"
else
	info "Installing the following Homebrew packages for you: ${install_list[@]}"
	brew install ${install_list[@]}
fi
	

# Install caskroom

install_caskroom() {
	local overwrite=false
	local name="Caskroom"

	if  ! $(brew tap | grep -lq "homebrew/cask")
	then
		info "Tapping Caskroom"
		brew tap homebrew/cask
	fi


	echo ""
	user "Install ${name}?: \n\
	[y]es, [n]o?"
	read -n 1 action

	case "$action" in
		y | Y )
			install=true;;
		n | N )
			install=false;;
		* )
		;;
	esac
	
  
	if [ "$install" == "true" ]
	then
		# Check to make sure we have all default casks
		installed_casks=$(brew cask list)
		install_cask_list=()


		# build list of casks to install
		for i in "${DEFAULT_CASKS[@]}"
		do
			contains "$installed_casks" $i
			r=$?
			if [[ "$r" -eq 1 ]]	
			then 
				#echo "$i added to install list"
				install_cask_list+=("$i");
			else
				echo "$i already installed"
			fi
		done
	
		
		# Install caskroom packages
		if [ ${#install_cask_list[@]} -eq 0 ]
		then 
			success "All default Caskroom packages already installed"
		else
			info "Installing the following Caskroom packages for you: ${install_cask_list[@]}"
			brew cask install ${install_cask_list[@]}
		fi
		
	else
      success "skipped ${name}"
	fi
}




install_caskroom

exit 0
