#!/bin/sh
#
# Settings for Node.js and NPM
#
# Downloads and installs latest node and npm using nv
# configures new default directory


# Capability to auto-install global modules here
# not currently in use @see https://www.sitepoint.com/solve-global-npm-module-dependency-problem/
# To finish configuration, mimic method used in homebrew/install

# Default global modules to install
# Add new ones here
#DEFAULT_MODULES=(		\
#	gulp 							\
#	gulp-util					\
#	bower 				
#)


# shortcut to this dotfiles path is $DOTS
export DOTS=$HOME/dotfiles

## Create default functions for interactive messages using solarized colors
source "$DOTS/functions/interactive"

# Get an install nvm
msg_info "Installing/Updating nvm for you..."
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash

msg_info "Exporting nvm config and loading"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# install latest node long term support relese
msg_info "Installing latest node.js LTS version and setting default"
nvm install --lts
nvm alias default lts/*


# @TODO - install gulp
# 