#!/bin/sh
#
# Settings for Node.js and NPM
#
# Downloads and installs latest node and npm using nv
# configures new default directory


# Capability to auto-install global modules here
# not currently in use @see https://www.sitepoint.com/solve-global-npm-module-dependency-problem/
# To finish configuration, mimic method used in homebrew/install

# Default global modules to install
# Add new ones here
DEFAULT_MODULES=(		\
	gulp 					\
	gulp-util			\
	grunt-init 			\
	grun-cli 			\
	bower 				
)


# Interaction functions
info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}


# Get an install nvm
info "Installing/Updating nvm for you..."
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash

info "Exporting nvm config and loading"
export NVM_DIR="/Users/grovesd/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 



# install latest node long term support relese
info "Installing latest node.js LTS version"
nvm install --lts


