#!/usr/bin/env bash
#
# bootstrap installs things.


cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)

# Exit immediately if a command exits with a non-zero status.
set -e

echo ''

# Interaction functions
info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}


# Create basic gitconfig.symlink file if one doesn't already exits
setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.symlink.example > git/gitconfig.symlink

    success 'gitconfig'
  fi
}


link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}


# Finds all the *.symlink files and runs links_file() on each
install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}


# Prompt to configure OS X Defaults
install_osx_defaults() {
	local overwrite=false
	local name="OS X defaults"

	echo ""
	user "Configure ${name}?: \n\
	[y]es, [n]o?"
	read -n 1 action

	case "$action" in
		y | Y )
			overwrite=true;;
		n | N )
			backup=false;;
		* )
		;;
	esac
  
	if [ "$overwrite" == "true" ]
	then
		info "Setting ${name}"
		
		if source $DOTFILES_ROOT/osx/set-defaults
		then
			success "${name} set"
		else
			fail "Error setting ${name}"
		fi
		
	else
      success "skipped ${name}"
	fi
}


# Install dependencies (Homebrew, etc.)
install_dependencies() {
	info "installing dependencies"
	if source bin/dot #> /tmp/dotfiles-dot 2>&1
	then
		success "dependencies installed"
	else
		fail "error installing dependencies"
	fi
}



setup_gitconfig
install_dotfiles
install_osx_defaults
install_dependencies


echo ''
echo '🦄  All installed!'
