#!/bin/sh
#
# Composer
#
# This installs and updates some of the common dependencies needed for PHP

# Default Composer packages to install (global only!)
# Add new ones here
DEFAULT_PKGS=(
)

# shortcut to this dotfiles path is $DOTS
export DOTS=$HOME/dotfiles


## Create default functions for interactive messages using solarized colors
source "$DOTS/functions/interactive"


# Check for Composer (global)
# Install or update
if test $(which composer)
then
	msg_info "Updating Composer for you..."
	composer self-update
	composer global update
else
	msg_info "Installing Composer for you..."

	if source "$DOTS/php/composer.install" #> /tmp/dotfiles-dot 2>&1
	then
		msg_success "Composer installed"
	else
		msg_fail "error installing Composer"
	fi
fi



# Check to make sure we have all default packages
installed_pkgs=$(composer global show)

install_list=()


# build list of packages to install
for i in "${DEFAULT_PKGS[@]}"
do
	if test $(echo "$installed_pkgs" | fgrep -lq "$i")	
	then 
		echo $?
		# echo "$i added to install list"
		install_list+=("$i");
		#else
		# echo "$i already installed"
	fi
done

# Install Composer packages
if [ ${#install_list[@]} -eq 0 ]
then 
	msg_success "All default global Composer packages already installed"
else
	msg_info "Installing the following Composer packages for you: ${install_list[@]}"
	brew install ${install_list[@]}
fi


exit 0
